[project]
name = "dewey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [

    "customtkinter>=5.2.2",

    "pyinstaller>=6.10.0",
]
